function dx = traj_model_stop(in1,udummy)
%TRAJ_MODEL_STOP
%    DX = TRAJ_MODEL_STOP(IN1,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    30-Jun-2024 01:48:58

kax = in1(5,:);
kay = in1(6,:);
kvx = in1(3,:);
kvy = in1(4,:);
t = in1(7,:);
t2 = t-1.0./2.0;
dx = [kax./2.0+kvx-t2.*(kax+kvx.*2.0);kay./2.0+kvy-t2.*(kay+kvy.*2.0);0.0;0.0;0.0;0.0;1.0];
end
