function dx = traj_model_accel(in1,udummy)
%TRAJ_MODEL_ACCEL
%    DX = TRAJ_MODEL_ACCEL(IN1,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    30-Jun-2024 01:48:58

kax = in1(5,:);
kay = in1(6,:);
kvx = in1(3,:);
kvy = in1(4,:);
t = in1(7,:);
dx = [kvx+kax.*t;kvy+kay.*t;0.0;0.0;0.0;0.0;1.0];
end
